#!/usr/bin/env bash
set -e

case "$(uname -s)" in
    Darwin)
        # macos
        darwin-rebuild build --flake .
        ;;
    Linux)
        # linux
        nixos-rebuild build --flake .
        ;;
    *)
        echo "Unsupported OS"
        exit 1
        ;;
esac

nix-diff /run/current-system result
nvd diff /run/current-system result
