# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  system.stateVersion = "24.11";
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # Use the systemd-boot EFI boot loader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  services.xserver.videoDrivers = [ "modesetting" ];
  environment.variables.TERMINAL = [ "kitty" ];
  networking.hostName = "thomas-t460";
  networking.useDHCP = lib.mkDefault true;
  networking.networkmanager.wifi.powersave = true;
  services.tlp.enable = true;

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.initrd.luks.devices.root = {
    device = "/dev/disk/by-uuid/1d961466-b1c8-4e5e-88e0-99e7d95dfa78";
    preLVM = true;
    allowDiscards = true;
  };

  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/89b66f19-17c1-45ee-9bf4-de2f798e33d1";
      fsType = "ext4";
      options = [ "discard" "noatime" "nodiratime" ];
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/10905317-4ed4-4ea8-add0-094a82bc5ac5";
      fsType = "ext4";
      options = [ "discard" "noatime" "nodiratime" "nodev" "nosuid" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/6414-6721";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" "discard" ];
    };

  fileSystems."/tmp" =
    {
      device = "tmpfs";
      options = [ "nodev" "nosuid" "nodiratime" "noatime" "size=2G" ];
      fsType = "tmpfs";
    };

  fileSystems."/run" =
    {
      device = "tmpfs";
      options = [ "nodev" "nosuid" "nodiratime" "noatime" "size=2G" ];
      fsType = "tmpfs";
    };

  fileSystems."/var/tmp" =
    {
      device = "tmpfs";
      options = [ "nodev" "nosuid" "nodiratime" "noatime" "size=2G" ];
      fsType = "tmpfs";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/157a7d5e-8a90-4a27-b00e-2d817639bf41"; }];
}
