# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix") ];

  system.stateVersion = "25.11"; # Did you read the comment?
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = true;

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.systemd-boot.editor = false;

  services.fprintd.enable = true;
  services.xserver.videoDrivers = [ "modesetting" ];
  environment.variables.TERMINAL = [ "kitty" ];
  networking.hostName = "thomas-x1gen9";
  networking.useDHCP = lib.mkDefault true;

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices.root = {
    device = "/dev/disk/by-uuid/bc191524-604b-40a3-b7e0-ed76c1f22937";
    preLVM = true;
    allowDiscards = true;
  };

  fileSystems."/" =
    {
      device = "/dev/mapper/vg0-root";
      fsType = "ext4";
      options = [ "discard" "noatime" "nodiratime" "x-systemd.device-timeout=infinity" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/752E-749C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" "discard" ];
    };

  fileSystems."/home" =
    {
      device = "/dev/mapper/vg0-home";
      fsType = "ext4";
      options = [ "discard" "noatime" "nodiratime" "nodev" "nosuid" ];
    };

  fileSystems."/nix" =
    {
      device = "/dev/mapper/vg0-nix";
      fsType = "ext4";
      options = [ "discard" "noatime" "nodiratime" ];
    };

  swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 16 * 1024;
    }
  ];

  environment.systemPackages = with pkgs; [
    spotify
    discord
  ];
}
