# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix") ];

  system.stateVersion = "25.11"; # Did you read the comment?
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = true;

  programs.captive-browser.interface = "wlp0s20f3";

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.systemd-boot.editor = false;

  services.fprintd.enable = true;
  # Disabled because fingerprint auth doesn't work well with apps that need sudo
  # in the background, e.g. VeraCrypt
  security.pam.services.sudo.fprintAuth = false;
  services.xserver.videoDrivers = [ "modesetting" ];
  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver # VA-API (iHD) userspace
      vpl-gpu-rt # oneVPL (QSV) runtime
      intel-compute-runtime # OpenCL (NEO) + Level Zero for Arc/Xe
    ];
  };

  environment.sessionVariables = {
    LIBVA_DRIVER_NAME = "iHD"; # Prefer the modern iHD backend
  };
  environment.variables.TERMINAL = [ "kitty" ];
  networking.hostName = "thomas-x1gen9";
  networking.useDHCP = lib.mkDefault true;

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices.root = {
    device = "/dev/disk/by-uuid/bc191524-604b-40a3-b7e0-ed76c1f22937";
    preLVM = true;
    allowDiscards = true;
  };

  services.autorandr.profiles = {
    "default" = {
      fingerprint = {
        "eDP-1" = "00ffffffffffff000e6f041400000000001e0104a51e137803d093a3554d9b240c4f5200000001010101010101010101010101010101353c80a070b02340302036002ebd10000018000000fd00303c4a4a0f010a202020202020000000fe0043534f542054330a2020202020000000fe004d4e453030374a41312d310a200014";
      };
      config = {
        "eDP-1" = { enable = true; primary = true; rate = "60.00"; position = "0x0"; mode = "1920x1200"; crtc = 0; gamma = "0.769:0.588:0.435"; };
        "DP-3" = { enable = false; };
      };
    };
    "desktop" = {
      fingerprint = {
        "DP-3" = "00ffffffffffff003103003400000000011e0103804f21782aee95a3544c99260f5054a54b0081c081809500a9c0b300d1c0714f0101f57c70a0d0a02950302035001e4e3100001a226870a0d0a02950302035001e4e3100001a000000fd0030653ca03c010a202020202020000000fc0050474d3334300a202020202020015f020337f14e010203040507901213145b1f5a5b23097f07830100006a030c001000384220000067d85dc401788003681a000001013065ed44d070a0d0a02950584045001e4e3100001ea448b86861a03250304035001e4e3100001e00000000000000000000000000000000000000000000000000000000000000000000000028";
        "eDP-1" = "00ffffffffffff000e6f041400000000001e0104a51e137803d093a3554d9b240c4f5200000001010101010101010101010101010101353c80a070b02340302036002ebd10000018000000fd00303c4a4a0f010a202020202020000000fe0043534f542054330a2020202020000000fe004d4e453030374a41312d310a200014";
      };
      config = {
        "DP-3" = { enable = true; primary = true; rate = "60.00"; position = "0x0"; mode = "3440x1440"; crtc = 1; gamma = "0.769:0.588:0.435"; };
        "eDP-1" = { enable = false; };
      };
    };
  };

  fileSystems."/" =
    {
      device = "/dev/mapper/vg0-root";
      fsType = "ext4";
      options = [ "discard" "noatime" "nodiratime" "x-systemd.device-timeout=infinity" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/752E-749C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" "discard" ];
    };

  fileSystems."/home" =
    {
      device = "/dev/mapper/vg0-home";
      fsType = "ext4";
      options = [ "discard" "noatime" "nodiratime" "nodev" "nosuid" ];
    };

  fileSystems."/nix" =
    {
      device = "/dev/mapper/vg0-nix";
      fsType = "ext4";
      options = [ "discard" "noatime" "nodiratime" ];
    };

  swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 16 * 1024;
    }
  ];

  environment.systemPackages = with pkgs; [
    spotify
    discord
  ];
}
