share_connections yes

copy --symlink-strategy=keep-path .vimrc
copy --symlink-strategy=keep-path .screenrc
copy --symlink-strategy=keep-path --dest=.bash_profile .sshbashrc
copy --dest=.aliases .sshaliases
