#!/usr/bin/env bash

# Drop sudo-specific options that pkexec does not use (-S, -p, -k, etc.)
args=()

while [ $# -gt 0 ]; do
  case "$1" in
    -S|-k|-E|--preserve-env|-n|--non-interactive|-v|--validate)
      shift
      ;;
    -p)
      shift 2
      ;;
    -p*)
      shift
      ;;
    -u)
      args+=(--user "$2")
      shift 2
      ;;
    --)
      shift
      args+=("$@")
      break
      ;;
    *)
      args+=("$1")
      shift
      ;;
  esac
done

exec pkexec "${args[@]}"
